apiVersion: v1
kind: Secret
metadata:
  name: chatpay-secrets
type: Opaque
data:
  postgres-password: Rmlyc3RQYm9zczAwLk5ha2F0YQ==
  stripe-secret-key: NnJYWmxrMzAwcWZYR3A1RnQ=
  jwt-secret: M2Rpd0o4QXVwRzJtTEZISVJWZlF2a2JLeWVOVFBvRDQ=